name: Code Quality Checks
on:
  push:
  branches-ignore:
    - $default-branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3.1.0-beta.2
        with:
          path:
          - .cache/pip
      - name: Install Venv
        run: pip install virtualenv
      - name: Activate Venv
        run: virtualenv venv
      - run: source venv/bin/activate
      - name: Install packages
        run: pip install -r requirements.txt

  black:
    runs-on: ubuntu-22.04
    steps:
      - name: Performing Black formatting
        run: pip install black
      - run: black $CI_PROJECT_DIR

  pylint:
    runs-on: ubuntu-22.04
    steps:
      - name: Performing lint checks
        run: pip install pylint
      - run: pylint $CI_PROJECT_NAME --disable=E0401